### ISSUE TITLE
Order Total Ommitted

### ISSUE THREAD

**Issue by kossanah** [ibrahimlawal/magento2-Profibro_Paystack#5]
The Paysatck M2 payment module is not taking Total Order Value. 
Only Cart Total value is passed to Paystack. Shipping not included

**Comment by ibrahimlawal** [comment]
Checking now! Thanks!

**Comment by AwoyoToyin** [comment]
Any news on this?
Apparently, the problem is that at the time this line executes
`checkoutConfig.totalsData.grand_total * 100`
the `grand_total` hasn't added the shipping cost or any other cost. The `grand_total` simply holds the `subtotal`.
To test this out, once the payment form loads after clicking the "place order" button, refresh the page and try clicking on the "place order" button. This time, it comes with all costs included

**Comment by AwoyoToyin** [comment]
@ibrahimlawal just fixed this and created a pull request

**Comment by AwoyoToyin** [comment]
@ibrahimlawal I believe this issue can be closed now, right?

**Comment by ibrahimlawal** [comment]
Yep

-----Original Message-----
