### ISSUE TITLE
Error On Redirecting To Page

### ISSUE THREAD

**Issue by steveamaza** [ibrahimlawal/magento2-Profibro_Paystack#9]
An integration of this plugin at http://bookmia.com/ runs into an error on successful payment.

*Details*
Magento 2.1.9
0.9.16 version of plugin
PHP 5.6.30

**Comment by AwoyoToyin** [comment]
Hello @steveamaza 
It is too much trouble to go through creating an account on your installation just to see what error you are running into.

Since you run into an error after successful payment, my best guess would be magento can not find the `Class Yabacon\Paystack` since this is needed for verifying a successful payment before redirecting to the success page. If it fails, you get stuck in the checkout page with an empty cart

You can simply fix this by running this command:
`composer require yabacon/paystack-php`

**Comment by steveamaza** [comment]
Thanks for coming through @AwoyoToyin. The problem has now been fixed. The user did not install using composer but imported directly to his installation. On going through the steps on the documentation, it started working fine.

**Comment by AwoyoToyin** [comment]
Good to know @steveamaza 
Sorry for the late reply though. Must have been a lot of trouble figuring the issue out.
